import { useCallback, useEffect, useMemo, useState } from "react";

import {
  getDashboardSummary,
  getRecoveryOpportunities,
  getPayments,
  getCustomers,
  getAnalyticsOverview,
  getPaymentMethodAnalytics,
  getFailureCategoryAnalytics,
} from "./services/api";

import "./App.css";

const P=['HIGH','MEDIUM','LOW'];
const NAV=[['Overview','⌂'],['Recovery','↻'],['Payments','▣'],['Customers','♙'],['Analytics','⌁']];
const EMPTY={payment_metrics:{total_transactions:0,successful_payments:0,failed_payments:0,success_rate:0,failure_rate:0,total_transaction_value:0},recovery_metrics:{total_failed_payments:0,revenue_at_risk:0,expected_recovery:0,recovery_rate:0,average_recovery_probability:0},priority_distribution:{HIGH:0,MEDIUM:0,LOW:0},payment_method_breakdown:[],failure_category_breakdown:[],top_opportunities:[]};
const n=x=>Number(x||0); const money=x=>`₹${n(x).toLocaleString('en-IN',{maximumFractionDigits:0})}`; const num=x=>n(x).toLocaleString('en-IN'); const pct=x=>`${(n(x)*100).toFixed(2)}%`; const nice=x=>String(x||'UNKNOWN').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
function normalize(x){return {...EMPTY,...x,payment_metrics:{...EMPTY.payment_metrics,...x?.payment_metrics},recovery_metrics:{...EMPTY.recovery_metrics,...x?.recovery_metrics},priority_distribution:{HIGH:n(x?.priority_distribution?.HIGH),MEDIUM:n(x?.priority_distribution?.MEDIUM),LOW:n(x?.priority_distribution?.LOW)},payment_method_breakdown:Array.isArray(x?.payment_method_breakdown)?x.payment_method_breakdown:[],failure_category_breakdown:Array.isArray(x?.failure_category_breakdown)?x.failure_category_breakdown:[],top_opportunities:Array.isArray(x?.top_opportunities)?x.top_opportunities:[]}}
function Header({eyebrow,title,tag}){return <div className="cardHead"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div>{tag&&<span className="tag">{tag}</span>}</div>}
function Metric({icon,title,value,sub,tone=''}){return <div className="metric"><div className={`metricIcon ${tone}`}>{icon}</div><div><span>{title}</span><strong>{value}</strong><small>{sub}</small></div></div>}
function Badge({p}){return <span className={`badge ${String(p||'LOW').toLowerCase()}`}>{p||'LOW'}</span>}
function Bars({items,name,count,moneyKey,moneyLabel}){if(!items.length)return <div className="empty">No analytics data available.</div>;const max=Math.max(...items.map(x=>n(x[count])),1);return <div className="bars">{items.slice(0,7).map((x,i)=><div className="barItem" key={String(x[name])+i}><div className="barLabel"><b>{nice(x[name])}</b><span>{num(x[count])}</span></div><div className="track"><div className="fill" style={{width:`${n(x[count])/max*100}%`}}/></div><div className="barMeta"><span>{moneyLabel}</span><b>{money(x[moneyKey])}</b></div></div>)}</div>}
function OpportunityTable({rows,onPriority}){return <section className="card"><Header eyebrow="ACTION QUEUE" title="Highest-value recovery opportunities" tag="AI RANKED"/>{!rows.length?<div className="empty">No recovery opportunities available.</div>:<div className="tableWrap"><table><thead><tr><th>TRANSACTION</th><th>METHOD</th><th>AMOUNT</th><th>RECOVERY PROB.</th><th>PRIORITY</th><th>ACTION</th><th>EXPECTED RECOVERY</th></tr></thead><tbody>{rows.map((x,i)=><tr key={x.transaction_id||i}><td><b>{x.transaction_id||'—'}</b><small>{x.customer_id||'—'}</small></td><td><span className="method">{x.payment_method||'—'}</span></td><td>{money(x.amount)}</td><td><div className="prob"><div className="probTrack"><div className="probFill" style={{width:`${Math.min(n(x.recovery_probability)*100,100)}%`}}/></div>{pct(x.recovery_probability)}</div></td><td><button className="plain" onClick={()=>onPriority?.(x.priority)}><Badge p={x.priority}/></button></td><td>{x.recommended_action||'Retry payment'}</td><td><b className="green">{money(x.expected_recovery_value)}</b></td></tr>)}</tbody></table></div>}</section>}

export default function App(){
 const [page,setPage]=useState('Overview'),[d,setD]=useState(EMPTY),[rows,setRows]=useState([]),[payments,setPayments]=useState([]),[customers,setCustomers]=useState([]),[methods,setMethods]=useState([]),[failures,setFailures]=useState([]),[analytics,setAnalytics]=useState(null),[filter,setFilter]=useState(''),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
 const load=useCallback(async(refresh=false)=>{if(refresh)setRefreshing(true);try{const [a,b,c,e,f,g,h]=await Promise.all([getDashboardSummary(),getRecoveryOpportunities('',100),getPayments('',100),getCustomers(100),getPaymentMethodAnalytics(),getFailureCategoryAnalytics(),getAnalyticsOverview()]);setD(normalize(a));setRows(b);setPayments(c);setCustomers(e);setMethods(Array.isArray(f)?f:[]);setFailures(Array.isArray(g)?g:[]);setAnalytics(h);setError('')}catch(x){console.error(x);setError(x.message||'Backend connection failed')}finally{setLoading(false);setRefreshing(false)}},[]);
 useEffect(()=>{let live=true;Promise.all([getDashboardSummary(),getRecoveryOpportunities('',100),getPayments('',100),getCustomers(100),getPaymentMethodAnalytics(),getFailureCategoryAnalytics(),getAnalyticsOverview()]).then(([a,b,c,e,f,g,h])=>{if(!live)return;setD(normalize(a));setRows(b);setPayments(c);setCustomers(e);setMethods(Array.isArray(f)?f:[]);setFailures(Array.isArray(g)?g:[]);setAnalytics(h)}).catch(x=>live&&setError(x.message||'Backend connection failed')).finally(()=>live&&setLoading(false));return()=>{live=false}},[]);
 const priority= d.priority_distribution,total=priority.HIGH+priority.MEDIUM+priority.LOW;
 const filterRows=async p=>{setFilter(p||'');try{setRows(await getRecoveryOpportunities(p||'',100));setPage('Recovery')}catch(x){setError(x.message)}};
 const sortedMethods=useMemo(()=>[...methods].sort((a,b)=>n(b.failed_payments)-n(a.failed_payments)),[methods]);const sortedFailures=useMemo(()=>[...failures].sort((a,b)=>n(b.failed_payments)-n(a.failed_payments)),[failures]);
 if(loading)return <div className="loading"><div className="logo">R</div><h1>RevenueOS</h1><p>Loading recovery intelligence...</p></div>;
 if(error&&!d.payment_metrics.total_transactions)return <div className="loading"><div className="errorCard"><div className="errorIcon">!</div><h1>RevenueOS could not connect</h1><p>{error}</p><button onClick={()=>load(false)}>↻ Retry</button><small>Start FastAPI at http://127.0.0.1:8000</small></div></div>;
 return <div className="shell"><aside className="side"><div className="brand"><div className="logo small">R</div><div><b>RevenueOS</b><span>Recovery Intelligence</span></div></div><div className="navTitle">WORKSPACE</div>{NAV.map(([x,ic])=><button key={x} className={`nav ${page===x?'active':''}`} onClick={()=>setPage(x)}><i>{ic}</i>{x}</button>)}<div className="grow"/><div className="ai"><b><span/> AI Engine Online</b><p>Recovery model active</p><div>ROC-AUC <strong>0.7155</strong></div></div><button className="settings" onClick={()=>setPage('Settings')}>⚙ Settings</button><small className="version">RevenueOS v1.0</small></aside><main className="main"><header className="top"><div><div className="eyebrow">REVENUE RECOVERY PLATFORM</div><h1>{page}</h1><p>Monitor failed payments and prioritize the highest-value recovery opportunities.</p></div><button className="refresh" onClick={()=>load(true)} disabled={refreshing}>{refreshing?'Refreshing...':'↻ Refresh data'}</button></header>{error&&<div className="alert">⚠ {error}</div>}
 {page==='Overview'&&<><div className="metrics"><Metric icon="◈" title="Total transactions" value={num(d.payment_metrics.total_transactions)} sub="Processed payments"/><Metric icon="×" title="Failed payments" value={num(d.payment_metrics.failed_payments)} sub={`${pct(d.payment_metrics.failure_rate)} failure rate`} tone="danger"/><Metric icon="✓" title="Payment success" value={pct(d.payment_metrics.success_rate)} sub={`${num(d.payment_metrics.successful_payments)} successful payments`} tone="success"/><Metric icon="!" title="Revenue at risk" value={money(d.recovery_metrics.revenue_at_risk)} sub={`${pct(d.recovery_metrics.recovery_rate)} recovery potential`} tone="warn"/></div><div className="grid2"><section className="card"><Header eyebrow="PRIORITIZATION" title="Recovery priority" tag="AI SCORED"/><div className="priorityList">{P.map(x=>{const v=priority[x],pc=total?v/total*100:0;return <button className="priority" key={x} onClick={()=>filterRows(x)}><div><span className={`dot ${x.toLowerCase()}`}/><b>{x}</b><strong>{num(v)}</strong></div><div className="track"><div className={`fill ${x.toLowerCase()}`} style={{width:`${pc}%`}}/></div><small>{pc.toFixed(1)}% of recovery cases · Click to view</small></button>})}</div><div className="miniGrid">{P.map(x=><button key={x} onClick={()=>filterRows(x)}><span className={`dot ${x.toLowerCase()}`}/>{x}<b>{num(priority[x])}</b></button>)}</div></section><section className="card"><Header eyebrow="PORTFOLIO" title="Priority mix" tag={`${num(total)} CASES`}/><div className="donutArea"><div className="donut" style={{background:`conic-gradient(#ef4444 0 ${(total?priority.HIGH/total:0)*100}%,#f59e0b ${(total?priority.HIGH/total:0)*100}% ${(total?(priority.HIGH+priority.MEDIUM)/total:0)*100}%,#94a3b8 ${(total?(priority.HIGH+priority.MEDIUM)/total:0)*100}% 100%)`}}><div><b>{num(total)}</b><small>cases</small></div></div><div className="legend">{P.map(x=><button key={x} onClick={()=>filterRows(x)}><span className={`dot ${x.toLowerCase()}`}/><div><b>{nice(x)} priority</b><small>{total?(priority[x]/total*100).toFixed(1):'0.0'}%</small></div><strong>{num(priority[x])}</strong></button>)}</div></div></section></div><div className="grid2"><section className="card"><Header eyebrow="PAYMENT INTELLIGENCE" title="Payment method exposure" tag="FAILED PAYMENTS"/><Bars items={sortedMethods} name="payment_method" count="failed_payments" moneyKey="revenue_at_risk" moneyLabel="At risk"/></section><section className="card"><Header eyebrow="FAILURE ANALYTICS" title="Failure categories" tag="TOP PATTERNS"/><Bars items={sortedFailures} name="failure_category" count="failed_payments" moneyKey="expected_recovery" moneyLabel="Expected recovery"/></section></div><OpportunityTable rows={d.top_opportunities.length?d.top_opportunities:rows.slice(0,10)} onPriority={filterRows}/></>}
 {page==='Recovery'&&<><div className="card"><Header eyebrow="RECOVERY WORKSPACE" title="Recovery opportunities" tag={`${num(rows.length)} SHOWN`}/><div className="filters">Filter by priority: <button className={!filter?'sel':''} onClick={()=>filterRows('')}>ALL</button>{P.map(x=><button className={filter===x?'sel':''} key={x} onClick={()=>filterRows(x)}>{x}</button>)}</div><OpportunityTable rows={rows} onPriority={filterRows}/></div></>}
 {page==='Payments'&&<><div className="metrics"><Metric icon="◈" title="Transactions" value={num(d.payment_metrics.total_transactions)} sub="All processed payments"/><Metric icon="✓" title="Successful" value={num(d.payment_metrics.successful_payments)} sub={pct(d.payment_metrics.success_rate)} tone="success"/><Metric icon="×" title="Failed" value={num(d.payment_metrics.failed_payments)} sub={pct(d.payment_metrics.failure_rate)} tone="danger"/><Metric icon="₹" title="Transaction value" value={money(d.payment_metrics.total_transaction_value)} sub="Processed payment value"/></div><DataTable title="Recent payment activity" rows={payments} headers={['transaction_id','customer_id','payment_method','amount','status','failure_reason']}/></>}
 {page==='Customers'&&<DataTable title="Customers with recovery exposure" rows={customers} headers={['customer_id','failed_payments','revenue_at_risk','expected_recovery','average_recovery_probability']}/>} 
 {page==='Analytics'&&<><div className="metrics"><Metric icon="×" title="Failure rate" value={pct(analytics?.failure_rate)} sub={`${num(analytics?.failed_payments)} failed payments`} tone="danger"/><Metric icon="!" title="Revenue at risk" value={money(analytics?.revenue_at_risk)} sub="Failed-payment exposure" tone="warn"/><Metric icon="↗" title="Expected recovery" value={money(analytics?.expected_recovery)} sub="AI recovery potential" tone="success"/><Metric icon="◎" title="Recovery rate" value={pct(analytics?.recovery_rate)} sub="Expected / at risk"/></div><div className="grid2"><section className="card"><Header eyebrow="PAYMENT METHODS" title="Failure exposure"/><Bars items={sortedMethods} name="payment_method" count="failed_payments" moneyKey="revenue_at_risk" moneyLabel="At risk"/></section><section className="card"><Header eyebrow="FAILURE ANALYTICS" title="Category breakdown"/><Bars items={sortedFailures} name="failure_category" count="failed_payments" moneyKey="expected_recovery" moneyLabel="Expected recovery"/></section></div></>}
 {page==='Settings'&&<section className="card"><Header eyebrow="SYSTEM" title="RevenueOS settings"/><div className="settingsGrid"><div><span>Backend API</span><b>http://127.0.0.1:8000</b><small>FastAPI</small></div><div><span>Recovery model</span><b>Active</b><small>ROC-AUC 0.7155</small></div><div><span>Data source</span><b>CSV datasets</b><small>payments.csv + recovery_recommendations.csv</small></div><div><span>Frontend</span><b>React + Vite</b><small>Connected dashboard</small></div></div></section>}
 </main></div>}

function DataTable({title,rows,headers}){return <section className="card"><Header eyebrow="DATA" title={title} tag={`${num(rows.length)} SHOWN`}/>{!rows.length?<div className="empty">No data available.</div>:<div className="tableWrap"><table><thead><tr>{headers.map(h=><th key={h}>{nice(h).toUpperCase()}</th>)}</tr></thead><tbody>{rows.slice(0,100).map((r,i)=><tr key={r.transaction_id||r.customer_id||i}>{headers.map(h=><td key={h}>{h.includes('amount')||h.includes('risk')||h.includes('recovery')&&h!=='average_recovery_probability'?money(r[h]):h==='average_recovery_probability'?pct(r[h]):h==='status'?<span className={`status ${String(r[h]).toLowerCase()}`}>{r[h]}</span>:nice(r[h]??'—')}</td>)}</tr>)}</tbody></table></div>}</section>}
